export class Skill {
    skill: string;
    entries = [];
    selectedEntry: { [key: string]: any } = {
        value: null,
        description: null
    };
    /**
     * @param  {string} skill
     * @description: The constructor initializes the class variable skill by the parameter oject injected into the constructor
     */
    constructor(skill: string) {
        this.skill = skill;
    }
    /**
     * @param  {string} skill
     * @description: The method intializes the class variable using the parameter object passed onto the method
     */
    update(skill: string): void {
        this.entries = [
            {
                description: 'High',
                id: 1,
                value: skill
            },
            {
                description: 'Medium',
                id: 2,
                value: skill
            },
            {
                description: 'Low',
                id: 3,
                value: skill
            }
        ];
        if (this.entries) {
            this.onSelectionChange(this.entries[0]);
        }
    }
    /**
     * @param  {Object} entry
     * @description: The method initializes the class variables by a new object generated by copying
     * the values of all of the enumerable own properties from source objects to a target object.
     */
    onSelectionChange(entry: Object): void {
        this.selectedEntry = Object.assign({}, this.selectedEntry, entry);
    }
}
